contact_links:
  - name: Feature request
    url: https://github.com/wosherco/zod-exporter/discussions
    about: Request features on discussions
  - name: Ask a question
    url: https://github.com/wosherco/zod-exporter/discussions
    about: Ask questions and discuss with other community members
